/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10518083;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Lenovo
 */
public class Buku extends javax.swing.JFrame {
     Connection conn;
    DefaultTableModel tabModel;
    /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        conn=koneksi.getConnection();
        setJTable();
    }
    /**
     * Creates new form Buku
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        txtJudulBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtKodeBuku = new javax.swing.JTextField();
        BClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BCari = new javax.swing.JButton();
        CBCari = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBuku = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        BTambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Status");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Penerbit");

        txtPenerbit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtJudulBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Judul Buku");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Kode Buku");

        txtKodeBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBukuActionPerformed(evt);
            }
        });

        BClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });

        CBCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Buku", "Judul Buku" }));

        TBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBuku);

        txtCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTambah)
                                .addGap(18, 18, 18)
                                .addComponent(BSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BEdit)
                                .addGap(18, 18, 18)
                                .addComponent(BBatal))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                    .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BCari))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BSimpan)
                    .addComponent(BHapus)
                    .addComponent(BEdit)
                    .addComponent(BBatal))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCari))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BClose)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel5.setText("DATA BUKU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeBukuActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        txtKodeBuku.setEnabled(true);         
        txtJudulBuku.setEnabled(true);         
        txtPenerbit.setEnabled(true); 
        txtStatus.setEnabled(true);
        BSimpan.setText("Simpan"); 
 
        BTambah.setEnabled(false); 
        BSimpan.setEnabled(true); 
        BEdit.setEnabled(false); 
        BBatal.setEnabled(true); 
        BHapus.setEnabled(false); 
        BClose.setEnabled(false);
    
        // TODO add your handling code here:

     //To change body of generated methods, choose Tools | Templates.
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
          if(BSimpan.getText().equalsIgnoreCase("Simpan"))             
            simpanData();         
        else 
            updateData(); 
 
        txtKodeBuku.setEnabled(false);         
        txtJudulBuku.setEnabled(false);         
        txtPenerbit.setEnabled(false);
        txtStatus.setEnabled(false);

        BTambah.setEnabled(true); 
        BSimpan.setEnabled(false); 
        BEdit.setEnabled(true); 
        BBatal.setEnabled(false); 
        BHapus.setEnabled(true); 
        BClose.setEnabled(true);
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        txtKodeBuku.setEnabled(false); 
        txtJudulBuku.setEnabled(true);
        txtPenerbit.setEnabled(true);
        txtStatus.setEnabled(false);
        BSimpan.setText("Update"); 
        ambilData_dari_JTable();
        
        BTambah.setEnabled(false); 
        BSimpan.setEnabled(true); 
        BEdit.setEnabled(false); 
        BBatal.setEnabled(true); 
        BHapus.setEnabled(false); 
        BClose.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BEditActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        hapusData();
        // TODO add your handling code here:
    }//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        txtKodeBuku.setText("");          
        txtJudulBuku.setText("");                 
        txtPenerbit.setText(""); 
        txtStatus.setText("");
 
       // Mengatur  Enable Tombol Dan Textfield           
       txtKodeBuku.setEnabled(false);         
       txtJudulBuku.setEnabled(false);         
       txtPenerbit.setEnabled(false);
       txtStatus.setEnabled(false);
 
        BTambah.setEnabled(true); 
        BSimpan.setEnabled(false); 
        BEdit.setEnabled(true); 
        BBatal.setEnabled(false); 
        BHapus.setEnabled(true); 
        BClose.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BBatalActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        String sql; 
        int pilih = CBCari.getSelectedIndex();         
        try {         
            if(pilih==0) 
        sql ="Select * from Buku WHERE KodeBuku ='" +txtCari.getText() + "'";         
            else 
        sql ="Select * from Buku WHERE JudulBuku Like '%" +txtCari.getText() + "%'"; 
 
        PreparedStatement st = conn.prepareStatement(sql);         
        ResultSet rs =st.executeQuery(); 
 
        hapusIsiJTable();         
        int no=0;         
        while (rs.next()) {             
            no++; 
             String KodeBuku = rs.getString("KodeBuku"); 
             String JudulBuku = rs.getString("JudulBuku"); 
             String Penerbit = rs.getString("Penerbit"); 
             String Status = rs.getString("Status");
             Object [] data = {no,KodeBuku, JudulBuku, Penerbit,Status};              
             tabModel.addRow(data); 
        } 
 
         if(tabModel.getRowCount()>0)          
           JOptionPane.showMessageDialog(this,"Data Ditemukan ");                 
         else 
            JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. "); 
 
      } 
      catch (SQLException se) {}  // Silahkan tambahkan sendiri informasi eksepsi    catch (SQLException se) {}

        // TODO add your handling code here:
    }//GEN-LAST:event_BCariActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
          dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     String reportSource;
String reportDest;
try{
 reportSource="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\buku.jrxml";
 reportDest="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\buku.html";
 
 JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);
 
 JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport, null,conn);
 
 net.sf.jasperreports.engine.JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
 
 JasperViewer.viewReport(jasperPrint, false);
 
}catch(Exception e){
 System.out.println(e);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }
private void setJTable(){ 
    String [] JudulKolom={"No","Kode Buku","Judul Buku","Penerbit","Status"};     
    tabModel = new DefaultTableModel(null, JudulKolom){ 
                  boolean[] canEdit = new boolean [] { false, false, false, false, false}; 
                  @Override 
                  public boolean isCellEditable(int rowIndex, int columnIndex) {                    return canEdit [columnIndex]; 
                  } 
              }; 
    
    TBuku.setModel(tabModel); 
    TBuku.setAutoResizeMode(TBuku.AUTO_RESIZE_OFF); 
    TBuku.getColumnModel().getColumn(0).setPreferredWidth(30); 
    TBuku.getColumnModel().getColumn(1).setPreferredWidth(100); 
    TBuku.getColumnModel().getColumn(2).setPreferredWidth(200);     
    TBuku.getColumnModel().getColumn(3).setPreferredWidth(300);
    TBuku.getColumnModel().getColumn(4).setPreferredWidth(300);
 
    getData(); }
private void getData(){     try{    
              // Membuat perintah sql  
        String sql="Select * from Buku"; 
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement               //Membuat Variabel Bertipe ResulSet 
             //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query         
             ResultSet rs=st.executeQuery();   // import java.sql.ResultSet; 
            // Menampilkan ke JTable  melalui tabModel 
        String KodeBuku,JudulBuku,Penerbit,Status;         
        int no=0;         
        while(rs.next()){          
            no=no+1; 
         KodeBuku=rs.getString("KodeBuku"); 
         JudulBuku=rs.getString("JudulBuku"); 
         Penerbit=rs.getString("Penerbit"); 
         Status=rs.getString("Status");
         Object Data[]={no,KodeBuku,JudulBuku,Penerbit,Status};          
         tabModel.addRow(Data); 
        } 
    } 
    catch (SQLException sqle) {                   
           System.out.println("Proses Query Gagal = " + sqle);            
           System.exit(0); 
    } 
    catch(Exception e){ 
           System.out.println("Koneksi Access Gagal " +e.getMessage());            
           System.exit(0); 
    } 
 
    }
void simpanData(){     
     try{             
            String sql="Insert into Buku values(?,?,?,?)"; 
            PreparedStatement st=conn.prepareStatement(sql); 
                st.setString(1, txtKodeBuku.getText());                 
                st.setString(2, txtJudulBuku.getText());                 
                st.setString(3, txtPenerbit.getText());
                st.setString(4, txtStatus.getText());
                int rs=st.executeUpdate(); 
 
            if(rs>0){ 
            JOptionPane.showMessageDialog(this,"Input Berhasil");        	    
            setJTable(); 
            } 
        } 
        catch (SQLException sqle) { 
           JOptionPane.showMessageDialog(this,"Input  Gagal = " + sqle.getMessage()); 
        } 
        catch(Exception e){ 
           JOptionPane.showMessageDialog(this,"Koneksi Gagal " +e.getMessage()); 
        } 
}
void ambilData_dari_JTable() {     
    int row = TBuku.getSelectedRow(); 
 	 
    // Mengambil data yang dipilih pada JTable 
    String KodeBuku = tabModel.getValueAt(row, 1).toString();     
    String JudulBuku = tabModel.getValueAt(row, 2).toString(); 
    String Penerbit = tabModel.getValueAt(row, 3).toString(); 
    String Status = tabModel.getValueAt(row, 4).toString();
    txtKodeBuku.setText(KodeBuku); 
    txtJudulBuku.setText(JudulBuku); 
    txtPenerbit.setText(Penerbit);
    txtStatus.setText(Status);
 	  }
public void hapusIsiJTable() { 
 
    int row = tabModel.getRowCount(); 
 
    for (int i = 0; i < row; i++) { 
      tabModel.removeRow(0); 
    }  
  }
public void tampilDataKeJTable() {
    hapusIsiJTable();

     try { 
        String sql="Select * from Buku"; 	 
        PreparedStatement st=conn.prepareStatement(sql); 	 
        ResultSet rs=st.executeQuery(); 	         
        String KodeBuku,JudulBuku,Penerbit,Status; 	         
        int no=0; 	         
        while(rs.next()){ 	 
         no=no+1; 
 
          KodeBuku=rs.getString("KodeBuku"); 
          JudulBuku=rs.getString("JudulBuku"); 
          Penerbit=rs.getString("Penerbit");
          Status=rs.getString("Status");
          Object Data[]={no,KodeBuku,JudulBuku,Penerbit,Status};           
          tabModel.addRow(Data);
      }   
     } 
 
    catch (Exception e) { }  // Isi informasi eksepsi 
}
public void updateData() { 	 
    // Konfirmasi sebelum melakukan perubahan data 
 
    int ok = JOptionPane.showConfirmDialog(this,"Anda Yakin Ingin Mengubah Data \n Dengan No Buku = '" + txtKodeBuku.getText() +   "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION); 	 
    // Apabila tombol Yes ditekan 	 
    if (ok == 0) { 	       
        try {  
        String sql ="UPDATE Buku SET JudulBuku = ?, Penerbit= ?, Status= ? WHERE KodeBuku = ?"; 	         
        PreparedStatement st = conn.prepareStatement(sql); 
 
         
          st.setString(1, txtJudulBuku.getText()); 	           
          st.setString(2, txtPenerbit.getText()); 	           
          st.setString(3, txtStatus.getText());
          st.setString(4, txtKodeBuku.getText());
          int rs=st.executeUpdate(); 	 
 	 
          if(rs>0){ 
 
            JOptionPane.showMessageDialog(this,"Edit Data Berhasil");        	 	    tampilDataKeJTable(); 
          }           
 	 
          txtKodeBuku.setText(""); 	           
          txtJudulBuku.setText(""); 	 
          txtPenerbit.setText("");
          txtStatus.setText("");
      }catch (SQLException se) {}  // Silahkan tambahkan Sendiri informasi Eksepsi 
 
    } 
     	 
  }
public void hapusData() { 
    // Konfirmasi sebelum melakukan penghapusan data     
    ambilData_dari_JTable(); 
    int ok = JOptionPane.showConfirmDialog(this,"Anda Yakin Ingin Menghapus Data\nDengan Kode Buku = '" + txtKodeBuku.getText() + 
         "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);     
    if (ok == 0) {     // Apabila tombol OK ditekan        
             try {        
        String sql = "DELETE FROM Buku WHERE KodeBuku = ?";          
        PreparedStatement st = conn.prepareStatement(sql);         
        st.setString(1, txtKodeBuku.getText()); 
 
        int rs=st.executeUpdate();         
        if(rs>0){ 
 
        tampilDataKeJTable(); 
         	JOptionPane.showMessageDialog(this,"Data Berhasil dihapus"); 
        } 
         	txtKodeBuku.setText("");         
                txtJudulBuku.setText("");          	
                txtPenerbit.setText(""); 
                txtStatus.setText("");
      } 
         catch (Exception se) {  // Silahkan tambahkan catch Exception yang lain 
                 JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. "); 
       } 
     } 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCari;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CBCari;
    private javax.swing.JTable TBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtKodeBuku;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
