/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10518083;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;      
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lenovo
 */
public class FAnggota extends javax.swing.JFrame {
    Connection conn;
    DefaultTableModel tabModel;
  
    
    /**
     * Creates new form FAnggota
     */
    public FAnggota() {
        initComponents();
        conn=koneksi.getConnection();
        setJTable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        CBCari = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        txtNoAnggota = new javax.swing.JTextField();
        BClose = new javax.swing.JButton();
        BPreview = new javax.swing.JButton();
        BCari = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAnggota = new javax.swing.JTable();
        cetak = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        CBCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoAnggota", "Nama" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel5.setText("DATA ANGGOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel5)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("No Anggota");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");

        BTambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        txtNoAnggota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoAnggotaActionPerformed(evt);
            }
        });

        BClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });

        BPreview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BPreview.setText("Preview");
        BPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPreviewActionPerformed(evt);
            }
        });

        BCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoAnggota", "Nama" }));

        txtCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No  Anggota", "Nama", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(TAnggota);

        cetak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cetak.setText("Cetak Kartu");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(BTambah)
                                .addGap(37, 37, 37)
                                .addComponent(BSimpan)
                                .addGap(43, 43, 43)
                                .addComponent(BEdit)
                                .addGap(39, 39, 39)
                                .addComponent(BBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BHapus))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(BPreview)
                                        .addGap(111, 111, 111)
                                        .addComponent(cetak)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BClose))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BCari))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTambah)
                            .addComponent(BSimpan)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BHapus))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BBatal)
                            .addComponent(BEdit))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCari))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPreview)
                    .addComponent(BClose)
                    .addComponent(cetak))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoAnggotaActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        txtNoAnggota.setEnabled(false); 
        txtNama.setEnabled(true);
        txtAlamat.setEnabled(true);
        BSimpan.setText("Update"); 
        ambilData_dari_JTable();
        
        BTambah.setEnabled(false); 
        BSimpan.setEnabled(true); 
        BEdit.setEnabled(false); 
        BBatal.setEnabled(true); 
        BHapus.setEnabled(false); 
        BClose.setEnabled(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        if(BSimpan.getText().equalsIgnoreCase("Simpan"))             
            simpanData();         
        else 
            updateData(); 
 
        txtNoAnggota.setEnabled(false);         
        txtNama.setEnabled(false);         
        txtAlamat.setEnabled(false);

        BTambah.setEnabled(true); 
        BSimpan.setEnabled(false); 
        BEdit.setEnabled(true); 
        BBatal.setEnabled(false); 
        BHapus.setEnabled(true); 
        BClose.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_BTambahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        hapusData();
        // TODO add your handling code here:
    }//GEN-LAST:event_BHapusActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
         String sql; 
        int pilih = CBCari.getSelectedIndex();         
        try {         
            if(pilih==0) 
        sql ="Select * from Anggota WHERE NoAnggota ='" +txtCari.getText() + "'";         
            else 
        sql ="Select * from Anggota WHERE Nama Like '%" +txtCari.getText() + "%'"; 
 
        PreparedStatement st = conn.prepareStatement(sql);         
        ResultSet rs =st.executeQuery(); 
 
        hapusIsiJTable();         
        int no=0;         
        while (rs.next()) {             
            no++; 
             String NoAnggota = rs.getString("NoAnggota"); 
             String Nama = rs.getString("Nama"); 
             String Alamat = rs.getString("Alamat"); 
             Object [] data = {no,NoAnggota, Nama, Alamat};              
             tabModel.addRow(data); 
        } 
 
         if(tabModel.getRowCount()>0)          
           JOptionPane.showMessageDialog(this,"Data Ditemukan ");                 
         else 
            JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. "); 
 
      } 
      catch (SQLException se) {}  // Silahkan tambahkan sendiri informasi eksepsi    catch (SQLException se) {}
      
        // TODO add your handling code here:
    }//GEN-LAST:event_BCariActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        txtNoAnggota.setText("");          
        txtNama.setText("");                 
        txtAlamat.setText(""); 
 
       // Mengatur  Enable Tombol Dan Textfield           
       txtNoAnggota.setEnabled(false);         
       txtNama.setEnabled(false);         
       txtAlamat.setEnabled(false); 
 
        BTambah.setEnabled(true); 
        BSimpan.setEnabled(false); 
        BEdit.setEnabled(true); 
        BBatal.setEnabled(false); 
        BHapus.setEnabled(true); 
        BClose.setEnabled(true); 

                                         

        // TODO add your handling code here:
    }//GEN-LAST:event_BBatalActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
          dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BCloseActionPerformed

    private void BPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPreviewActionPerformed
String reportSource;
String reportDest;
try{
 reportSource="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\anggota.jrxml";
 reportDest="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\anggota.html";
 
 JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);
 
 JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport, null,conn);
 
 net.sf.jasperreports.engine.JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
 
 JasperViewer.viewReport(jasperPrint, false);
 
}catch(Exception e){
 System.out.println(e);
}


        // TODO add your handling code here:
    }//GEN-LAST:event_BPreviewActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
int row =  TAnggota.getSelectedRow();
     String No_Anggota = tabModel.getValueAt(row, 1).toString();
     String reportSource;
     String reportDest;// TODO add your handling code here:
     
     Map<String,Object> param=new HashMap<String,Object>();
     param.put("noanggota", No_Anggota);
     try{
      reportSource="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\KA.jrxml";
      reportDest="C:\\xampp\\htdocs\\P10518083\\src\\p10518083\\KA.html";
    JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);
 
 JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport, param,conn);
 
 net.sf.jasperreports.engine.JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
 
 JasperViewer.viewReport(jasperPrint, false);
 
     }catch(Exception e){
 System.out.println(e);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAnggota().setVisible(true);
            }
        });
    }
private void setJTable(){ 
    String [] JudulKolom={"No","No Anggota","Nama Anggota","Alamat"};     
    tabModel = new DefaultTableModel(null, JudulKolom){ 
                  boolean[] canEdit = new boolean [] { false, false, false, false}; 
                  @Override 
                  public boolean isCellEditable(int rowIndex, int columnIndex) {                    return canEdit [columnIndex]; 
                  } 
              }; 
    TAnggota.setModel(tabModel); 
    TAnggota.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
    TAnggota.getColumnModel().getColumn(0).setPreferredWidth(30); 
    TAnggota.getColumnModel().getColumn(1).setPreferredWidth(100); 
    TAnggota.getColumnModel().getColumn(2).setPreferredWidth(200);     
    TAnggota.getColumnModel().getColumn(3).setPreferredWidth(300); 
 
    getData(); }
private void getData(){     try{    
              // Membuat perintah sql  
        String sql="Select * from Anggota"; 
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement               //Membuat Variabel Bertipe ResulSet 
             //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query         
             ResultSet rs=st.executeQuery();   // import java.sql.ResultSet; 
            // Menampilkan ke JTable  melalui tabModel 
        String NoAnggota,Nama,Alamat;         
        int no=0;         
        while(rs.next()){          
            no=no+1; 
         NoAnggota=rs.getString("NoAnggota"); 
         Nama=rs.getString("Nama"); 
         Alamat=rs.getString("Alamat"); 
 
         Object Data[]={no,NoAnggota,Nama,Alamat};          tabModel.addRow(Data); 
        } 
    } 
    catch (SQLException sqle) {                   
           System.out.println("Proses Query Gagal = " + sqle);            System.exit(0); 
    } 
    catch(Exception e){ 
           System.out.println("Koneksi Access Gagal " +e.getMessage());            System.exit(0); 
    } 
 
    }
    void simpanData(){     
     try{             
            String sql="Insert into Anggota values(?,?,?)"; 
            PreparedStatement st=conn.prepareStatement(sql); 
                st.setString(1, txtNoAnggota.getText());                 
                st.setString(2, txtNama.getText());                 
                st.setString(3, txtAlamat.getText());             
                int rs=st.executeUpdate(); 
 
            if(rs>0){ 
            JOptionPane.showMessageDialog(this,"Input Berhasil");        	    
            setJTable(); 
            } 
        } 
        catch (SQLException sqle) { 
           JOptionPane.showMessageDialog(this,"Input  Gagal = " + sqle.getMessage()); 
        } 
        catch(Exception e){ 
           JOptionPane.showMessageDialog(this,"Koneksi Gagal " +e.getMessage()); 
        } 
} 
void ambilData_dari_JTable() {     
    int row = TAnggota.getSelectedRow(); 
 	 
    // Mengambil data yang dipilih pada JTable 
    String NoAnggota = tabModel.getValueAt(row, 1).toString();     
    String Nama = tabModel.getValueAt(row, 2).toString(); 
    String Alamat = tabModel.getValueAt(row, 3).toString(); 
    
    txtNoAnggota.setText(NoAnggota); 
    txtNama.setText(Nama); 
    txtAlamat.setText(Alamat); 
 	  }
public void hapusIsiJTable() { 
 
    int row = tabModel.getRowCount(); 
 
    for (int i = 0; i < row; i++) { 
      tabModel.removeRow(0); 
    }  
  } 
public void tampilDataKeJTable() {
    hapusIsiJTable();

     try { 
        String sql="Select * from Anggota"; 	 
        PreparedStatement st=conn.prepareStatement(sql); 	 
        ResultSet rs=st.executeQuery(); 	         String NoAnggota,Nama,Alamat; 	         int no=0; 	         while(rs.next()){ 	 
         no=no+1; 
 
         NoAnggota=rs.getString("NoAnggota"); 
          Nama=rs.getString("Nama"); 
          Alamat=rs.getString("Alamat"); 
          Object Data[]={no,NoAnggota,Nama,Alamat};           tabModel.addRow(Data);
      }    } 
 
    catch (Exception e) { }  // Isi informasi eksepsi 
}
public void updateData() { 	 
    // Konfirmasi sebelum melakukan perubahan data 
 
    int ok = JOptionPane.showConfirmDialog(this,"Anda Yakin Ingin Mengubah Data \n Dengan  = '" + txtNoAnggota.getText() +   "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION); 	 
    // Apabila tombol Yes ditekan 	 
    if (ok == 0) { 	       
        try {  
        String sql ="UPDATE Anggota SET Nama = ?, Alamat= ? WHERE NoAnggota = ?"; 	         
        PreparedStatement st = conn.prepareStatement(sql); 
 
         
          st.setString(1, txtNama.getText()); 	           
          st.setString(2, txtAlamat.getText()); 	           
          st.setString(3, txtNoAnggota.getText()); 	           
          int rs=st.executeUpdate(); 	 
 	 
          if(rs>0){ 
 
            JOptionPane.showMessageDialog(this,"Edit Data Berhasil");        	 	    tampilDataKeJTable(); 
          }           
 	 
          txtNoAnggota.setText(""); 	           
          txtNama.setText(""); 	 
          txtAlamat.setText("");              	 
      }catch (SQLException se) {}  // Silahkan tambahkan Sendiri informasi Eksepsi 
 
    } 
     	 
  } 
public void hapusData() { 
    // Konfirmasi sebelum melakukan penghapusan data     
    ambilData_dari_JTable(); 
    int ok = JOptionPane.showConfirmDialog(this,"Anda Yakin Ingin Menghapus Data\nDengan No Anggota = '" + txtNoAnggota.getText() + 
         "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);     if (ok == 0) {     // Apabila tombol OK ditekan        
             try {        
        String sql = "DELETE FROM Anggota WHERE NoAnggota = ?";          
        PreparedStatement st = conn.prepareStatement(sql);         
        st.setString(1, txtNoAnggota.getText()); 
 
        int rs=st.executeUpdate();         
        if(rs>0){ 
 
        tampilDataKeJTable(); 
         	JOptionPane.showMessageDialog(this,"Data Berhasil dihapus"); 
        } 
         	txtNoAnggota.setText("");         
                txtNama.setText("");          	
                txtAlamat.setText(""); 
      } 
         catch (Exception se) {  // Silahkan tambahkan catch Exception yang lain 
                 JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. "); 
       } 
     } 
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCari;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BPreview;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CBCari;
    private javax.swing.JTable TAnggota;
    private javax.swing.JButton cetak;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoAnggota;
    // End of variables declaration//GEN-END:variables

    private void setJTabel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class JasperExportManager {

        private static void exportReportToHtmlFile(JasperPrint jasperPrint, String reportDest) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public JasperExportManager() {
        }
    }

    

}

 
