/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10518083;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Lenovo
 */
public class FUtama extends javax.swing.JFrame {
  Connection conn;
    /**
     * Creates new form FUtama
     */
    public FUtama() {
        initComponents();
        conn=koneksi.getConnection();
        MEdit.setVisible(false); // menu Edit
        MPelayanan.setVisible(false); // menu Pelayanan
        MLaporan.setVisible(false); // menu Laporan
        MLogin.setEnabled(true); // menu item Login
        MLogout.setEnabled(false); // menu item Logout
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLogin = new javax.swing.JPanel();
        LUsername = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        LLogin = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        BLogin = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MLogin = new javax.swing.JMenuItem();
        MLogout = new javax.swing.JMenuItem();
        MExit = new javax.swing.JMenuItem();
        MEdit = new javax.swing.JMenu();
        MAnggota = new javax.swing.JMenuItem();
        MBuku = new javax.swing.JMenuItem();
        MPelayanan = new javax.swing.JMenu();
        MPeminjaman = new javax.swing.JMenuItem();
        MPengembalian = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        MPeminjaman1 = new javax.swing.JMenuItem();
        MPengembalian1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PLogin.setBackground(new java.awt.Color(255, 153, 153));

        LUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LUsername.setText("Username");

        LPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LPassword.setText("Password");

        LLogin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        LLogin.setText("LOGIN");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        BLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BLogin.setText("Login");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });

        BCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCancel.setText("Cancel");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("SAFIRA AULIA UTAMI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("10518083");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p10518083/1.jpg"))); // NOI18N

        javax.swing.GroupLayout PLoginLayout = new javax.swing.GroupLayout(PLogin);
        PLogin.setLayout(PLoginLayout);
        PLoginLayout.setHorizontalGroup(
            PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLoginLayout.createSequentialGroup()
                .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LPassword)
                            .addComponent(LUsername)
                            .addComponent(BLogin))
                        .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PLoginLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtPassword)))
                            .addGroup(PLoginLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(BCancel))))
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(LLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(97, 97, 97))
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        PLoginLayout.setVerticalGroup(
            PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPassword)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BLogin)
                            .addComponent(BCancel)))
                    .addGroup(PLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 51));

        jMenu1.setText("File");

        MLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        MLogin.setText("Login");
        MLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLoginActionPerformed(evt);
            }
        });
        jMenu1.add(MLogin);

        MLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MLogout.setText("Logout");
        MLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(MLogout);

        MExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MExit.setText("Exit");
        MExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MExitActionPerformed(evt);
            }
        });
        jMenu1.add(MExit);

        jMenuBar1.add(jMenu1);

        MEdit.setText("Edit");
        MEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEditActionPerformed(evt);
            }
        });

        MAnggota.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MAnggota.setText("Anggota");
        MAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAnggotaActionPerformed(evt);
            }
        });
        MEdit.add(MAnggota);

        MBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MBuku.setText("Buku");
        MBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBukuActionPerformed(evt);
            }
        });
        MEdit.add(MBuku);

        jMenuBar1.add(MEdit);

        MPelayanan.setText("Pelayanan");

        MPeminjaman.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MPeminjaman.setText("Peminjaman");
        MPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPeminjamanActionPerformed(evt);
            }
        });
        MPelayanan.add(MPeminjaman);

        MPengembalian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        MPengembalian.setText("Pengembalian");
        MPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPengembalianActionPerformed(evt);
            }
        });
        MPelayanan.add(MPengembalian);

        jMenuBar1.add(MPelayanan);

        MLaporan.setText("Laporan");

        MPeminjaman1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_OPEN_BRACKET, java.awt.event.InputEvent.CTRL_MASK));
        MPeminjaman1.setText("Peminjaman");
        MPeminjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPeminjaman1ActionPerformed(evt);
            }
        });
        MLaporan.add(MPeminjaman1);

        MPengembalian1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_OPEN_BRACKET, java.awt.event.InputEvent.SHIFT_MASK));
        MPengembalian1.setText("Pengembalian");
        MPengembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPengembalian1ActionPerformed(evt);
            }
        });
        MLaporan.add(MPengembalian1);

        jMenuBar1.add(MLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MLoginActionPerformed

    private void MLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLogoutActionPerformed
        // TODO add your handling code here:
        PLogin.setVisible(true);
        PLogin.setEnabled(true);
        LLogin.setVisible(true);
        LLogin.setEnabled(true);
        LUsername.setVisible(true);
        LUsername.setEnabled(true);
        LPassword.setVisible(true);
        LPassword.setEnabled(true);
        txtUsername.setVisible(true);
        txtUsername.setEnabled(true);
        txtPassword.setVisible(true);
        txtPassword.setEnabled(true);
        BLogin.setVisible(true);
        BLogin.setEnabled(true);
        BCancel.setVisible(true);
        BCancel.setEnabled(true);
        MEdit.setVisible(false); // menu Edit
        MPelayanan.setVisible(false); // menu Pelayanan
        MLaporan.setVisible(false); // menu Laporan
        MLogin.setEnabled(true); // menu item Login
        MLogout.setEnabled(false); // menu item Logout
        MExit.setEnabled(true); // menu Exit
        txtUsername.setText("");
        txtPassword.setText("");

    }//GEN-LAST:event_MLogoutActionPerformed

    private void MExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_MExitActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        // TODO add your handling code here:
        String sql;
        String username=txtUsername.getText();
        String password=txtPassword.getText();
        try {
            sql ="Select * from user WHERE username ='" +txtUsername.getText() + "'";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();
            if (rs.next()) {
                String pass = rs.getString("password");
                String bagian = rs.getString("bagian");
                if (password.equals(pass)){
                    JOptionPane.showMessageDialog(this, "Login Berhasil");
                    if(bagian.equals("Sirkulasi")){
                        MEdit.setVisible(false); // menu Edit
                        MPelayanan.setVisible(true);  // menu Pelayanan
                        MLaporan.setVisible(true);  // menu Laporan

                        MLogin.setEnabled(false); // menu item Login
                        MLogout.setEnabled(true);  // menu item Logout

                        PLogin.setVisible(false);
                        PLogin.setEnabled(false);
                        LLogin.setVisible(false);
                        LLogin.setEnabled(false);
                        LUsername.setVisible(false);
                        LUsername.setEnabled(false);
                        LPassword.setVisible(false);
                        LPassword.setEnabled(false);
                        txtUsername.setVisible(false);
                        txtUsername.setEnabled(false);
                        txtPassword.setVisible(false);
                        txtPassword.setEnabled(false);
                        BLogin.setVisible(false);
                        BLogin.setEnabled(false);
                        BCancel.setVisible(false);
                        BCancel.setEnabled(false);
                    }
                    else
                    {
                        MEdit.setVisible(true); // menu Edit
                        MPelayanan.setVisible(true); // menu Pelayanan
                        MLaporan.setVisible(true); // menu Laporan

                        MLogin.setEnabled(false); // menu item Login
                        MLogout.setEnabled(true);  // menu item Logout
                        PLogin.setVisible(false);
                        PLogin.setEnabled(false);
                        LLogin.setVisible(false);
                        LLogin.setEnabled(false);
                        LUsername.setVisible(false);
                        LUsername.setEnabled(false);
                        LPassword.setVisible(false);
                        LPassword.setEnabled(false);
                        txtUsername.setVisible(false);
                        txtUsername.setEnabled(false);
                        txtPassword.setVisible(false);
                        txtPassword.setEnabled(false);
                        BLogin.setVisible(false);
                        BLogin.setEnabled(false);
                        BCancel.setVisible(false);
                        BCancel.setEnabled(false);
                    }
                }
                else
                JOptionPane.showMessageDialog(this, "Ada Kesalahan pada Username/Password");
            } else
            JOptionPane.showMessageDialog(this, "Ada Kesalahan pada Username/Password");
        }
        catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_BLoginActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_BCancelActionPerformed

    private void MEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEditActionPerformed

    private void MBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBukuActionPerformed
        // TODO add your handling code here:
        Buku buku = new Buku();
        buku.setVisible(true);
        buku.setLocationRelativeTo(null);
    }//GEN-LAST:event_MBukuActionPerformed

    private void MAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAnggotaActionPerformed
        FAnggota fanggota = new FAnggota();
        fanggota.setVisible(true);
        fanggota.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_MAnggotaActionPerformed

    private void MPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPeminjamanActionPerformed
        // TODO add your handling code here:
        FPeminjaman fpeminjaman = new FPeminjaman();
        fpeminjaman.setVisible(true);
        fpeminjaman.setLocationRelativeTo(null);
    }//GEN-LAST:event_MPeminjamanActionPerformed

    private void MPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPengembalianActionPerformed
        FPengembalian fpengembalian = new FPengembalian();
        fpengembalian.setVisible(true);
        fpengembalian.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_MPengembalianActionPerformed

    private void MPeminjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPeminjaman1ActionPerformed
        LPinjam lpinjam = new LPinjam();
        lpinjam.setVisible(true);
        lpinjam.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_MPeminjaman1ActionPerformed

    private void MPengembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPengembalian1ActionPerformed
         LKembali lkembali = new LKembali();
        lkembali.setVisible(true);
        lkembali.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_MPengembalian1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel LLogin;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LUsername;
    private javax.swing.JMenuItem MAnggota;
    private javax.swing.JMenuItem MBuku;
    private javax.swing.JMenu MEdit;
    private javax.swing.JMenuItem MExit;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenuItem MLogin;
    private javax.swing.JMenuItem MLogout;
    private javax.swing.JMenu MPelayanan;
    private javax.swing.JMenuItem MPeminjaman;
    private javax.swing.JMenuItem MPeminjaman1;
    private javax.swing.JMenuItem MPengembalian;
    private javax.swing.JMenuItem MPengembalian1;
    private javax.swing.JPanel PLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
